### ISSUE TITLE
ERROR: Paired-end mapping found, but not supported!

### ISSUE THREAD

**Issue by nungerleider** [zavolanlab/TECtool#1]
Hi, I tried running this command:

tectool --annotation GRCh38.87_support_level_1/*gtf  --polyasites GRCh38.87_support_level_1/*bed --bam SRR1290424.Aligned.sortedByCoord.out.bam --genome GRCh38.87_support_level_1/*fa --verbose

And I got the following error:

Counting feature regions |                                | 1/83227ERROR: Paired-end mapping found, but not supported!

Your manuscript suggests paired end reads can be analyzed by this program - could there be another issue with my BAM file (i.e. supplemental alignments, etc) that causes this error?

Thanks!

Nate

**Comment by fgypas** [comment]
Hi @nungerleider 

Sorry, at the moment you have to use one of the two mates in case of paired-end reads. Maybe it was not clear the way we wrote it.

Best
Foivos

**Comment by peterkilfeather** [comment]
Can you recommend the best way to do this? Do we have to re-map with just one read mate fastq file?

**Comment by fgypas** [comment]
Hi @langkilfeather. Yes, you need to re-map one of the two mates.
